
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_CI_BASE_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}-base
  DOCKER_CI_SRC_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}-src
  ARACHNE_PYTHONPATH: ${CI_PROJECT_DIR}/python
  TVM_LIBRARY_PATH: ${CI_PROJECT_DIR}/build/tvm
  CUDA_VISIBLE_DEVICES: 7

check-format-diff:
  stage: .pre
  image: python:3.6
  tags:
    - docker
    - dgx1
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH
  script:
    - python3 -m pip install black isort flake8
    - isort python --diff --check
    - black python --diff --check
    - flake8 --show-source --statistic


build-image:
  stage: build
  image: docker:19.03.14
  tags:
    - docker
    - dgx1
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build --target base -t ${DOCKER_CI_BASE_IMAGE} -f docker/devel-gpu.Dockerfile docker
    - docker build -t ${DOCKER_CI_SRC_IMAGE} -f docker/devel-gpu.Dockerfile --build-arg GITLAB_USERNAME=gitlab-ci-token --build-arg GITLAB_ACCESS_TOKEN=${CI_JOB_TOKEN} docker
    - docker push ${DOCKER_CI_BASE_IMAGE}

test-arachne:
  stage: test
  image: ${DOCKER_CI_BASE_IMAGE}
  needs: ['build-image']
  tags:
    - docker
    - dgx1
  before_script:
    - export PYTHONPATH=${ARACHNE_PYTHONPATH}:$PYTHONPATH
    - poetry install
    - poetry run ./scripts/install_tvm.sh
    - poetry run ./scripts/install_torch2trt.sh
  script:
    - poetry run pytest tests --forked

test-doc-build:
  stage: test
  image: ${DOCKER_CI_BASE_IMAGE}
  needs: ['build-image']
  tags:
    - docker
    - dgx1
  before_script:
    - export PYTHONPATH=${ARACHNE_PYTHONPATH}:$PYTHONPATH
    - poetry install
    - poetry run ./scripts/install_tvm.sh
    - poetry run ./scripts/install_torch2trt.sh
  script:
    - poetry run sphinx-build docs docs/_build
  artifacts:
    paths:
      - docs/_build

pages:
  stage: deploy
  image: ${DOCKER_CI_BASE_IMAGE}
  needs:
    - job: test-doc-build
      artifacts: true
  tags:
    - docker
    - dgx1
  script:
    - mv docs/_build public
  artifacts:
    paths:
      - public
  only:
  - feature/v0.2

cleanup-image:
  stage: .post
  image: docker:19.03.14
  tags:
    - docker
    - dgx1
  when: always
  script:
    - docker image rm -f ${DOCKER_CI_BASE_IMAGE} || true
    - docker image rm -f ${DOCKER_CI_SRC_IMAGE} || true
