version: 2

submodules:
  include: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.6"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
