[tool.poetry]
name = "arachne"
version = "0.0.0"
description = "\"A library for testing your DNN models on your edge devices\""
authors = ["Takafumi Kubota <takafumi.kubota@fixstars.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
