[tool.poetry]
name = "arachne"
version = "0.0.0"
description = "A framework for compile and benchmark DNN inferences on the devices"
authors = ["Akira Maruoka <akira.maruoka@fixstars.com>"]
packages = [
    { include = "arachne", from = "python"},
    { include = "3rdparty/tvm/python/tvm"},
]
include = ["3rdparty/tvm"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.6.2"
numpy = "1.19.4"
decorator = "^5.1.0"
attrs = "^21.2.0"
tornado = "^6.1"
psutil = "^5.8.0"
xgboost = "^1.4.2"
cloudpickle = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.9.2"
black = "^21.6b0"
pre-commit = "*"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0", "wheel", "setuptools", "cmake", "ninja"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py36']
include = '(\.pyi?$)'
exclude = '''

(
  /(
      \.github
    | \.git
    | \.vscode
    | 3rdparty
    | docker\/
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["python/arachne"]
filter_files = true
skip_glob = "*/3rdparty/**/*,*/docker/**/*,*/.vscode/**/*,*/.git/**/*,*/.github/**/*"
