# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import msg_response_pb2 as msg__response__pb2
import onnxruntime_pb2 as onnxruntime__pb2
import runtime_message_pb2 as runtime__message__pb2


class ONNXRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/onnxruntime.ONNXRuntime/Init',
                request_serializer=onnxruntime__pb2.ONNXInitRequest.SerializeToString,
                response_deserializer=msg__response__pb2.MsgResponse.FromString,
                )
        self.SetInput = channel.stream_unary(
                '/onnxruntime.ONNXRuntime/SetInput',
                request_serializer=runtime__message__pb2.SetInputRequest.SerializeToString,
                response_deserializer=msg__response__pb2.MsgResponse.FromString,
                )
        self.Run = channel.unary_unary(
                '/onnxruntime.ONNXRuntime/Run',
                request_serializer=runtime__message__pb2.RunRequest.SerializeToString,
                response_deserializer=msg__response__pb2.MsgResponse.FromString,
                )
        self.Benchmark = channel.unary_unary(
                '/onnxruntime.ONNXRuntime/Benchmark',
                request_serializer=runtime__message__pb2.BenchmarkRequest.SerializeToString,
                response_deserializer=runtime__message__pb2.BenchmarkResponse.FromString,
                )
        self.GetOutput = channel.unary_stream(
                '/onnxruntime.ONNXRuntime/GetOutput',
                request_serializer=runtime__message__pb2.GetOutputRequest.SerializeToString,
                response_deserializer=runtime__message__pb2.GetOutputResponse.FromString,
                )


class ONNXRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInput(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Benchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ONNXRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=onnxruntime__pb2.ONNXInitRequest.FromString,
                    response_serializer=msg__response__pb2.MsgResponse.SerializeToString,
            ),
            'SetInput': grpc.stream_unary_rpc_method_handler(
                    servicer.SetInput,
                    request_deserializer=runtime__message__pb2.SetInputRequest.FromString,
                    response_serializer=msg__response__pb2.MsgResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=runtime__message__pb2.RunRequest.FromString,
                    response_serializer=msg__response__pb2.MsgResponse.SerializeToString,
            ),
            'Benchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.Benchmark,
                    request_deserializer=runtime__message__pb2.BenchmarkRequest.FromString,
                    response_serializer=runtime__message__pb2.BenchmarkResponse.SerializeToString,
            ),
            'GetOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOutput,
                    request_deserializer=runtime__message__pb2.GetOutputRequest.FromString,
                    response_serializer=runtime__message__pb2.GetOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onnxruntime.ONNXRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ONNXRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onnxruntime.ONNXRuntime/Init',
            onnxruntime__pb2.ONNXInitRequest.SerializeToString,
            msg__response__pb2.MsgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetInput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/onnxruntime.ONNXRuntime/SetInput',
            runtime__message__pb2.SetInputRequest.SerializeToString,
            msg__response__pb2.MsgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onnxruntime.ONNXRuntime/Run',
            runtime__message__pb2.RunRequest.SerializeToString,
            msg__response__pb2.MsgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Benchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onnxruntime.ONNXRuntime/Benchmark',
            runtime__message__pb2.BenchmarkRequest.SerializeToString,
            runtime__message__pb2.BenchmarkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/onnxruntime.ONNXRuntime/GetOutput',
            runtime__message__pb2.GetOutputRequest.SerializeToString,
            runtime__message__pb2.GetOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
