# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_response_pb2 as msg__response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_status.proto',
  package='server_status',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13server_status.proto\x12\rserver_status\x1a\x12msg_response.proto\"\r\n\x0bLockRequest\"\x0f\n\rUnlockRequest2z\n\x0cServerStatus\x12\x32\n\x04Lock\x12\x1a.server_status.LockRequest\x1a\x0c.MsgResponse\"\x00\x12\x36\n\x06Unlock\x12\x1c.server_status.UnlockRequest\x1a\x0c.MsgResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[msg__response__pb2.DESCRIPTOR,])




_LOCKREQUEST = _descriptor.Descriptor(
  name='LockRequest',
  full_name='server_status.LockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=71,
)


_UNLOCKREQUEST = _descriptor.Descriptor(
  name='UnlockRequest',
  full_name='server_status.UnlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['LockRequest'] = _LOCKREQUEST
DESCRIPTOR.message_types_by_name['UnlockRequest'] = _UNLOCKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LockRequest = _reflection.GeneratedProtocolMessageType('LockRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCKREQUEST,
  '__module__' : 'server_status_pb2'
  # @@protoc_insertion_point(class_scope:server_status.LockRequest)
  })
_sym_db.RegisterMessage(LockRequest)

UnlockRequest = _reflection.GeneratedProtocolMessageType('UnlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKREQUEST,
  '__module__' : 'server_status_pb2'
  # @@protoc_insertion_point(class_scope:server_status.UnlockRequest)
  })
_sym_db.RegisterMessage(UnlockRequest)



_SERVERSTATUS = _descriptor.ServiceDescriptor(
  name='ServerStatus',
  full_name='server_status.ServerStatus',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='Lock',
    full_name='server_status.ServerStatus.Lock',
    index=0,
    containing_service=None,
    input_type=_LOCKREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Unlock',
    full_name='server_status.ServerStatus.Unlock',
    index=1,
    containing_service=None,
    input_type=_UNLOCKREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERSTATUS)

DESCRIPTOR.services_by_name['ServerStatus'] = _SERVERSTATUS

# @@protoc_insertion_point(module_scope)
