# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfliteruntime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_response_pb2 as msg__response__pb2
import runtime_message_pb2 as runtime__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfliteruntime.proto',
  package='tfliteruntime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13tfliteruntime.proto\x12\rtfliteruntime\x1a\x12msg_response.proto\x1a\x15runtime_message.proto\"<\n\x11TfLiteInitRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x13\n\x0bnum_threads\x18\x02 \x01(\x05\x32\x8b\x02\n\rTfLiteRuntime\x12\x38\n\x04Init\x12 .tfliteruntime.TfLiteInitRequest\x1a\x0c.MsgResponse\"\x00\x12.\n\x08SetInput\x12\x10.SetInputRequest\x1a\x0c.MsgResponse\"\x00(\x01\x12\"\n\x03Run\x12\x0b.RunRequest\x1a\x0c.MsgResponse\"\x00\x12\x34\n\tBenchmark\x12\x11.BenchmarkRequest\x1a\x12.BenchmarkResponse\"\x00\x12\x36\n\tGetOutput\x12\x11.GetOutputRequest\x1a\x12.GetOutputResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[msg__response__pb2.DESCRIPTOR,runtime__message__pb2.DESCRIPTOR,])




_TFLITEINITREQUEST = _descriptor.Descriptor(
  name='TfLiteInitRequest',
  full_name='tfliteruntime.TfLiteInitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='tfliteruntime.TfLiteInitRequest.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_threads', full_name='tfliteruntime.TfLiteInitRequest.num_threads', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['TfLiteInitRequest'] = _TFLITEINITREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TfLiteInitRequest = _reflection.GeneratedProtocolMessageType('TfLiteInitRequest', (_message.Message,), {
  'DESCRIPTOR' : _TFLITEINITREQUEST,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.TfLiteInitRequest)
  })
_sym_db.RegisterMessage(TfLiteInitRequest)



_TFLITERUNTIME = _descriptor.ServiceDescriptor(
  name='TfLiteRuntime',
  full_name='tfliteruntime.TfLiteRuntime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=411,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='tfliteruntime.TfLiteRuntime.Init',
    index=0,
    containing_service=None,
    input_type=_TFLITEINITREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInput',
    full_name='tfliteruntime.TfLiteRuntime.SetInput',
    index=1,
    containing_service=None,
    input_type=runtime__message__pb2._SETINPUTREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='tfliteruntime.TfLiteRuntime.Run',
    index=2,
    containing_service=None,
    input_type=runtime__message__pb2._RUNREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Benchmark',
    full_name='tfliteruntime.TfLiteRuntime.Benchmark',
    index=3,
    containing_service=None,
    input_type=runtime__message__pb2._BENCHMARKREQUEST,
    output_type=runtime__message__pb2._BENCHMARKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutput',
    full_name='tfliteruntime.TfLiteRuntime.GetOutput',
    index=4,
    containing_service=None,
    input_type=runtime__message__pb2._GETOUTPUTREQUEST,
    output_type=runtime__message__pb2._GETOUTPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TFLITERUNTIME)

DESCRIPTOR.services_by_name['TfLiteRuntime'] = _TFLITERUNTIME

# @@protoc_insertion_point(module_scope)
