# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfliteruntime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stream_data_pb2 as stream__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfliteruntime.proto',
  package='tfliteruntime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13tfliteruntime.proto\x12\rtfliteruntime\x1a\x11stream_data.proto\"-\n\x0bMsgResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x0bInitRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x13\n\x0bnum_threads\x18\x02 \x01(\x05\"J\n\x0fSetInputRequest\x12\x0f\n\x05index\x18\x01 \x01(\x05H\x00\x12\x1e\n\x0cnp_arr_chunk\x18\x02 \x01(\x0b\x32\x06.ChunkH\x00\x42\x06\n\x04\x64\x61ta\"\x0f\n\rInvokeRequest\"!\n\x10GetOutputRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"$\n\x11GetOutputResponse\x12\x0f\n\x07np_data\x18\x01 \x01(\x0c\x32\xbd\x02\n\x13TfliteRuntimeServer\x12@\n\x04Init\x12\x1a.tfliteruntime.InitRequest\x1a\x1a.tfliteruntime.MsgResponse\"\x00\x12J\n\x08SetInput\x12\x1e.tfliteruntime.SetInputRequest\x1a\x1a.tfliteruntime.MsgResponse\"\x00(\x01\x12\x44\n\x06Invoke\x12\x1c.tfliteruntime.InvokeRequest\x1a\x1a.tfliteruntime.MsgResponse\"\x00\x12R\n\tGetOutput\x12\x1f.tfliteruntime.GetOutputRequest\x1a .tfliteruntime.GetOutputResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[stream__data__pb2.DESCRIPTOR,])




_MSGRESPONSE = _descriptor.Descriptor(
  name='MsgResponse',
  full_name='tfliteruntime.MsgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='tfliteruntime.MsgResponse.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='tfliteruntime.MsgResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=102,
)


_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='tfliteruntime.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='tfliteruntime.InitRequest.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_threads', full_name='tfliteruntime.InitRequest.num_threads', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=158,
)


_SETINPUTREQUEST = _descriptor.Descriptor(
  name='SetInputRequest',
  full_name='tfliteruntime.SetInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='tfliteruntime.SetInputRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='np_arr_chunk', full_name='tfliteruntime.SetInputRequest.np_arr_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='tfliteruntime.SetInputRequest.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=160,
  serialized_end=234,
)


_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='tfliteruntime.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=251,
)


_GETOUTPUTREQUEST = _descriptor.Descriptor(
  name='GetOutputRequest',
  full_name='tfliteruntime.GetOutputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='tfliteruntime.GetOutputRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=286,
)


_GETOUTPUTRESPONSE = _descriptor.Descriptor(
  name='GetOutputResponse',
  full_name='tfliteruntime.GetOutputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='np_data', full_name='tfliteruntime.GetOutputResponse.np_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=324,
)

_SETINPUTREQUEST.fields_by_name['np_arr_chunk'].message_type = stream__data__pb2._CHUNK
_SETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _SETINPUTREQUEST.fields_by_name['index'])
_SETINPUTREQUEST.fields_by_name['index'].containing_oneof = _SETINPUTREQUEST.oneofs_by_name['data']
_SETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _SETINPUTREQUEST.fields_by_name['np_arr_chunk'])
_SETINPUTREQUEST.fields_by_name['np_arr_chunk'].containing_oneof = _SETINPUTREQUEST.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['MsgResponse'] = _MSGRESPONSE
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['SetInputRequest'] = _SETINPUTREQUEST
DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['GetOutputRequest'] = _GETOUTPUTREQUEST
DESCRIPTOR.message_types_by_name['GetOutputResponse'] = _GETOUTPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgResponse = _reflection.GeneratedProtocolMessageType('MsgResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGRESPONSE,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.MsgResponse)
  })
_sym_db.RegisterMessage(MsgResponse)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

SetInputRequest = _reflection.GeneratedProtocolMessageType('SetInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETINPUTREQUEST,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.SetInputRequest)
  })
_sym_db.RegisterMessage(SetInputRequest)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEREQUEST,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.InvokeRequest)
  })
_sym_db.RegisterMessage(InvokeRequest)

GetOutputRequest = _reflection.GeneratedProtocolMessageType('GetOutputRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTPUTREQUEST,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.GetOutputRequest)
  })
_sym_db.RegisterMessage(GetOutputRequest)

GetOutputResponse = _reflection.GeneratedProtocolMessageType('GetOutputResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTPUTRESPONSE,
  '__module__' : 'tfliteruntime_pb2'
  # @@protoc_insertion_point(class_scope:tfliteruntime.GetOutputResponse)
  })
_sym_db.RegisterMessage(GetOutputResponse)



_TFLITERUNTIMESERVER = _descriptor.ServiceDescriptor(
  name='TfliteRuntimeServer',
  full_name='tfliteruntime.TfliteRuntimeServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='tfliteruntime.TfliteRuntimeServer.Init',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInput',
    full_name='tfliteruntime.TfliteRuntimeServer.SetInput',
    index=1,
    containing_service=None,
    input_type=_SETINPUTREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Invoke',
    full_name='tfliteruntime.TfliteRuntimeServer.Invoke',
    index=2,
    containing_service=None,
    input_type=_INVOKEREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutput',
    full_name='tfliteruntime.TfliteRuntimeServer.GetOutput',
    index=3,
    containing_service=None,
    input_type=_GETOUTPUTREQUEST,
    output_type=_GETOUTPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TFLITERUNTIMESERVER)

DESCRIPTOR.services_by_name['TfliteRuntimeServer'] = _TFLITERUNTIMESERVER

# @@protoc_insertion_point(module_scope)
