# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tvmruntime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stream_data_pb2 as stream__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tvmruntime.proto',
  package='tvmruntime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10tvmruntime.proto\x12\ntvmruntime\x1a\x11stream_data.proto\"-\n\x0bMsgResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0bInitRequest\x12\x14\n\x0cpackage_path\x18\x01 \x01(\t\"6\n\x05Index\x12\x11\n\x07index_i\x18\x01 \x01(\x05H\x00\x12\x11\n\x07index_s\x18\x02 \x01(\tH\x00\x42\x07\n\x05index\"]\n\x0fSetInputRequest\x12\"\n\x05index\x18\x01 \x01(\x0b\x32\x11.tvmruntime.IndexH\x00\x12\x1e\n\x0cnp_arr_chunk\x18\x02 \x01(\x0b\x32\x06.ChunkH\x00\x42\x06\n\x04\x64\x61ta\"\x0c\n\nRunRequest\"B\n\x10\x42\x65nchmarkRequest\x12\x0e\n\x06warmup\x18\x01 \x01(\x05\x12\x0e\n\x06repeat\x18\x02 \x01(\x05\x12\x0e\n\x06number\x18\x03 \x01(\x05\"T\n\x11\x42\x65nchmarkResponse\x12\x0f\n\x07mean_ts\x18\x01 \x01(\x02\x12\x0e\n\x06std_ts\x18\x02 \x01(\x02\x12\x0e\n\x06max_ts\x18\x03 \x01(\x02\x12\x0e\n\x06min_ts\x18\x04 \x01(\x02\"!\n\x10GetOutputRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"$\n\x11GetOutputResponse\x12\x0f\n\x07np_data\x18\x01 \x01(\x0c\x32\xe8\x02\n\x10TVMRuntimeServer\x12:\n\x04Init\x12\x17.tvmruntime.InitRequest\x1a\x17.tvmruntime.MsgResponse\"\x00\x12\x44\n\x08SetInput\x12\x1b.tvmruntime.SetInputRequest\x1a\x17.tvmruntime.MsgResponse\"\x00(\x01\x12\x38\n\x03Run\x12\x16.tvmruntime.RunRequest\x1a\x17.tvmruntime.MsgResponse\"\x00\x12J\n\tBenchmark\x12\x1c.tvmruntime.BenchmarkRequest\x1a\x1d.tvmruntime.BenchmarkResponse\"\x00\x12L\n\tGetOutput\x12\x1c.tvmruntime.GetOutputRequest\x1a\x1d.tvmruntime.GetOutputResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[stream__data__pb2.DESCRIPTOR,])




_MSGRESPONSE = _descriptor.Descriptor(
  name='MsgResponse',
  full_name='tvmruntime.MsgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='tvmruntime.MsgResponse.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='tvmruntime.MsgResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=96,
)


_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='tvmruntime.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_path', full_name='tvmruntime.InitRequest.package_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=133,
)


_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='tvmruntime.Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_i', full_name='tvmruntime.Index.index_i', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index_s', full_name='tvmruntime.Index.index_s', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='index', full_name='tvmruntime.Index.index',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=135,
  serialized_end=189,
)


_SETINPUTREQUEST = _descriptor.Descriptor(
  name='SetInputRequest',
  full_name='tvmruntime.SetInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='tvmruntime.SetInputRequest.index', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='np_arr_chunk', full_name='tvmruntime.SetInputRequest.np_arr_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='tvmruntime.SetInputRequest.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=191,
  serialized_end=284,
)


_RUNREQUEST = _descriptor.Descriptor(
  name='RunRequest',
  full_name='tvmruntime.RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=298,
)


_BENCHMARKREQUEST = _descriptor.Descriptor(
  name='BenchmarkRequest',
  full_name='tvmruntime.BenchmarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warmup', full_name='tvmruntime.BenchmarkRequest.warmup', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeat', full_name='tvmruntime.BenchmarkRequest.repeat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='tvmruntime.BenchmarkRequest.number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=366,
)


_BENCHMARKRESPONSE = _descriptor.Descriptor(
  name='BenchmarkResponse',
  full_name='tvmruntime.BenchmarkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean_ts', full_name='tvmruntime.BenchmarkResponse.mean_ts', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='std_ts', full_name='tvmruntime.BenchmarkResponse.std_ts', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_ts', full_name='tvmruntime.BenchmarkResponse.max_ts', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_ts', full_name='tvmruntime.BenchmarkResponse.min_ts', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=452,
)


_GETOUTPUTREQUEST = _descriptor.Descriptor(
  name='GetOutputRequest',
  full_name='tvmruntime.GetOutputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='tvmruntime.GetOutputRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=487,
)


_GETOUTPUTRESPONSE = _descriptor.Descriptor(
  name='GetOutputResponse',
  full_name='tvmruntime.GetOutputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='np_data', full_name='tvmruntime.GetOutputResponse.np_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=525,
)

_INDEX.oneofs_by_name['index'].fields.append(
  _INDEX.fields_by_name['index_i'])
_INDEX.fields_by_name['index_i'].containing_oneof = _INDEX.oneofs_by_name['index']
_INDEX.oneofs_by_name['index'].fields.append(
  _INDEX.fields_by_name['index_s'])
_INDEX.fields_by_name['index_s'].containing_oneof = _INDEX.oneofs_by_name['index']
_SETINPUTREQUEST.fields_by_name['index'].message_type = _INDEX
_SETINPUTREQUEST.fields_by_name['np_arr_chunk'].message_type = stream__data__pb2._CHUNK
_SETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _SETINPUTREQUEST.fields_by_name['index'])
_SETINPUTREQUEST.fields_by_name['index'].containing_oneof = _SETINPUTREQUEST.oneofs_by_name['data']
_SETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _SETINPUTREQUEST.fields_by_name['np_arr_chunk'])
_SETINPUTREQUEST.fields_by_name['np_arr_chunk'].containing_oneof = _SETINPUTREQUEST.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['MsgResponse'] = _MSGRESPONSE
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
DESCRIPTOR.message_types_by_name['SetInputRequest'] = _SETINPUTREQUEST
DESCRIPTOR.message_types_by_name['RunRequest'] = _RUNREQUEST
DESCRIPTOR.message_types_by_name['BenchmarkRequest'] = _BENCHMARKREQUEST
DESCRIPTOR.message_types_by_name['BenchmarkResponse'] = _BENCHMARKRESPONSE
DESCRIPTOR.message_types_by_name['GetOutputRequest'] = _GETOUTPUTREQUEST
DESCRIPTOR.message_types_by_name['GetOutputResponse'] = _GETOUTPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgResponse = _reflection.GeneratedProtocolMessageType('MsgResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGRESPONSE,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.MsgResponse)
  })
_sym_db.RegisterMessage(MsgResponse)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.Index)
  })
_sym_db.RegisterMessage(Index)

SetInputRequest = _reflection.GeneratedProtocolMessageType('SetInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETINPUTREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.SetInputRequest)
  })
_sym_db.RegisterMessage(SetInputRequest)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.RunRequest)
  })
_sym_db.RegisterMessage(RunRequest)

BenchmarkRequest = _reflection.GeneratedProtocolMessageType('BenchmarkRequest', (_message.Message,), {
  'DESCRIPTOR' : _BENCHMARKREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.BenchmarkRequest)
  })
_sym_db.RegisterMessage(BenchmarkRequest)

BenchmarkResponse = _reflection.GeneratedProtocolMessageType('BenchmarkResponse', (_message.Message,), {
  'DESCRIPTOR' : _BENCHMARKRESPONSE,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.BenchmarkResponse)
  })
_sym_db.RegisterMessage(BenchmarkResponse)

GetOutputRequest = _reflection.GeneratedProtocolMessageType('GetOutputRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTPUTREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.GetOutputRequest)
  })
_sym_db.RegisterMessage(GetOutputRequest)

GetOutputResponse = _reflection.GeneratedProtocolMessageType('GetOutputResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTPUTRESPONSE,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.GetOutputResponse)
  })
_sym_db.RegisterMessage(GetOutputResponse)



_TVMRUNTIMESERVER = _descriptor.ServiceDescriptor(
  name='TVMRuntimeServer',
  full_name='tvmruntime.TVMRuntimeServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='tvmruntime.TVMRuntimeServer.Init',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInput',
    full_name='tvmruntime.TVMRuntimeServer.SetInput',
    index=1,
    containing_service=None,
    input_type=_SETINPUTREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='tvmruntime.TVMRuntimeServer.Run',
    index=2,
    containing_service=None,
    input_type=_RUNREQUEST,
    output_type=_MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Benchmark',
    full_name='tvmruntime.TVMRuntimeServer.Benchmark',
    index=3,
    containing_service=None,
    input_type=_BENCHMARKREQUEST,
    output_type=_BENCHMARKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutput',
    full_name='tvmruntime.TVMRuntimeServer.GetOutput',
    index=4,
    containing_service=None,
    input_type=_GETOUTPUTREQUEST,
    output_type=_GETOUTPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TVMRUNTIMESERVER)

DESCRIPTOR.services_by_name['TVMRuntimeServer'] = _TVMRUNTIMESERVER

# @@protoc_insertion_point(module_scope)
