# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tvmruntime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_response_pb2 as msg__response__pb2
import runtime_message_pb2 as runtime__message__pb2
import stream_data_pb2 as stream__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tvmruntime.proto',
  package='tvmruntime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10tvmruntime.proto\x12\ntvmruntime\x1a\x12msg_response.proto\x1a\x15runtime_message.proto\x1a\x11stream_data.proto\"&\n\x0eTVMInitRequest\x12\x14\n\x0cpackage_path\x18\x01 \x01(\t\"6\n\x05Index\x12\x11\n\x07index_i\x18\x01 \x01(\x05H\x00\x12\x11\n\x07index_s\x18\x02 \x01(\tH\x00\x42\x07\n\x05index\"`\n\x12TVMSetInputRequest\x12\"\n\x05index\x18\x01 \x01(\x0b\x32\x11.tvmruntime.IndexH\x00\x12\x1e\n\x0cnp_arr_chunk\x18\x02 \x01(\x0b\x32\x06.ChunkH\x00\x42\x06\n\x04\x64\x61ta2\x90\x02\n\nTVMRuntime\x12\x32\n\x04Init\x12\x1a.tvmruntime.TVMInitRequest\x1a\x0c.MsgResponse\"\x00\x12<\n\x08SetInput\x12\x1e.tvmruntime.TVMSetInputRequest\x1a\x0c.MsgResponse\"\x00(\x01\x12\"\n\x03Run\x12\x0b.RunRequest\x1a\x0c.MsgResponse\"\x00\x12\x34\n\tBenchmark\x12\x11.BenchmarkRequest\x1a\x12.BenchmarkResponse\"\x00\x12\x36\n\tGetOutput\x12\x11.GetOutputRequest\x1a\x12.GetOutputResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[msg__response__pb2.DESCRIPTOR,runtime__message__pb2.DESCRIPTOR,stream__data__pb2.DESCRIPTOR,])




_TVMINITREQUEST = _descriptor.Descriptor(
  name='TVMInitRequest',
  full_name='tvmruntime.TVMInitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_path', full_name='tvmruntime.TVMInitRequest.package_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=132,
)


_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='tvmruntime.Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_i', full_name='tvmruntime.Index.index_i', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index_s', full_name='tvmruntime.Index.index_s', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='index', full_name='tvmruntime.Index.index',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=134,
  serialized_end=188,
)


_TVMSETINPUTREQUEST = _descriptor.Descriptor(
  name='TVMSetInputRequest',
  full_name='tvmruntime.TVMSetInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='tvmruntime.TVMSetInputRequest.index', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='np_arr_chunk', full_name='tvmruntime.TVMSetInputRequest.np_arr_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='tvmruntime.TVMSetInputRequest.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=190,
  serialized_end=286,
)

_INDEX.oneofs_by_name['index'].fields.append(
  _INDEX.fields_by_name['index_i'])
_INDEX.fields_by_name['index_i'].containing_oneof = _INDEX.oneofs_by_name['index']
_INDEX.oneofs_by_name['index'].fields.append(
  _INDEX.fields_by_name['index_s'])
_INDEX.fields_by_name['index_s'].containing_oneof = _INDEX.oneofs_by_name['index']
_TVMSETINPUTREQUEST.fields_by_name['index'].message_type = _INDEX
_TVMSETINPUTREQUEST.fields_by_name['np_arr_chunk'].message_type = stream__data__pb2._CHUNK
_TVMSETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _TVMSETINPUTREQUEST.fields_by_name['index'])
_TVMSETINPUTREQUEST.fields_by_name['index'].containing_oneof = _TVMSETINPUTREQUEST.oneofs_by_name['data']
_TVMSETINPUTREQUEST.oneofs_by_name['data'].fields.append(
  _TVMSETINPUTREQUEST.fields_by_name['np_arr_chunk'])
_TVMSETINPUTREQUEST.fields_by_name['np_arr_chunk'].containing_oneof = _TVMSETINPUTREQUEST.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['TVMInitRequest'] = _TVMINITREQUEST
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
DESCRIPTOR.message_types_by_name['TVMSetInputRequest'] = _TVMSETINPUTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TVMInitRequest = _reflection.GeneratedProtocolMessageType('TVMInitRequest', (_message.Message,), {
  'DESCRIPTOR' : _TVMINITREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.TVMInitRequest)
  })
_sym_db.RegisterMessage(TVMInitRequest)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.Index)
  })
_sym_db.RegisterMessage(Index)

TVMSetInputRequest = _reflection.GeneratedProtocolMessageType('TVMSetInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _TVMSETINPUTREQUEST,
  '__module__' : 'tvmruntime_pb2'
  # @@protoc_insertion_point(class_scope:tvmruntime.TVMSetInputRequest)
  })
_sym_db.RegisterMessage(TVMSetInputRequest)



_TVMRUNTIME = _descriptor.ServiceDescriptor(
  name='TVMRuntime',
  full_name='tvmruntime.TVMRuntime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=561,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='tvmruntime.TVMRuntime.Init',
    index=0,
    containing_service=None,
    input_type=_TVMINITREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInput',
    full_name='tvmruntime.TVMRuntime.SetInput',
    index=1,
    containing_service=None,
    input_type=_TVMSETINPUTREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='tvmruntime.TVMRuntime.Run',
    index=2,
    containing_service=None,
    input_type=runtime__message__pb2._RUNREQUEST,
    output_type=msg__response__pb2._MSGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Benchmark',
    full_name='tvmruntime.TVMRuntime.Benchmark',
    index=3,
    containing_service=None,
    input_type=runtime__message__pb2._BENCHMARKREQUEST,
    output_type=runtime__message__pb2._BENCHMARKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutput',
    full_name='tvmruntime.TVMRuntime.GetOutput',
    index=4,
    containing_service=None,
    input_type=runtime__message__pb2._GETOUTPUTREQUEST,
    output_type=runtime__message__pb2._GETOUTPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TVMRUNTIME)

DESCRIPTOR.services_by_name['TVMRuntime'] = _TVMRUNTIME

# @@protoc_insertion_point(module_scope)
