apiVersion: apps/v1
kind: Deployment
metadata:
  name: arachne-tvm-rpc-server-$DEVICE
  labels:
    app: arachne-tvm-rpc-server-$DEVICE
  annotations:
    app.gitlab.com/env: development
    app.gitlab.com/app: arachne-arachne
spec:
  replicas: $NODE_NUM
  selector:
    matchLabels:
      app: arachne-tvm-rpc-server-$DEVICE
  template:
    metadata:
      labels:
        app: arachne-tvm-rpc-server-$DEVICE
      annotations:
        app.gitlab.com/env: development
        app.gitlab.com/app: arachne-arachne
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: device
                  operator: In
                  values:
                    - $DEVICE
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - arachne-tvm-rpc-server-$DEVICE
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tvm-rpc-server
          image:  gitlab.fixstars.com:5005/arachne/arachne/l4t_tvm_rpc_server:latest
          command: ["/usr/bin/python3"]
          args: ["-m", "tvm.exec.rpc_server", "--tracker=192.168.5.211:9190", "--key=$DEVICE"]
          tty: true
          imagePullPolicy: Always
      hostNetwork: true
      imagePullSecrets:
        - name: gitlab-registry
