name: Test CI

on:
  workflow_dispatch:

jobs:

  run1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test CI
      run: echo $GITHUB_RUN_ID

  run2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test CI2
      run: echo $GITHUB_RUN_ID